require('plugin.mason-lspconfig')
require('plugin.cmp')
require('plugin.treesitter')
require('plugin.autopairs')
require('plugin.telescope')
require('plugin.tree')
require('plugin.colorizer')
require('plugin.colorscheme')
